import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache all files generated by the build process
// The self.__WB_MANIFEST array is injected by Vite/Workbox at build
precacheAndRoute(self.__WB_MANIFEST || []);

// Example: cache all images
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
    plugins: [],
  })
);

// Example: cache API responses
registerRoute(
  ({ url }) => url.origin === 'https://davemovie-henna.vercel.app',
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
  })
);

// Listen for message to skip waiting and activate new SW immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});